Add files via upload

diff --git a/.github/workflows/build-onecloud.yml b/.github/workflows/build-onecloud.yml
--- a/.github/workflows/build-onecloud.yml
+++ b/.github/workflows/build-onecloud.yml
@@ -28,6 +28,7 @@ env:
   CONFIG_FILE: onecloud.config
   DIY_P1_SH: diy-part1.sh
   DIY_P2_SH: diy-part2-onecloud.sh
+  GEN_BURN_IMG_SH: gen_burn_img.sh
   UPLOAD_BIN_DIR: false
   UPLOAD_FIRMWARE: true
   UPLOAD_RELEASE: false
@@ -38,6 +39,17 @@ jobs:
     runs-on: ubuntu-22.04
 
     steps:
+    - name: 释放磁盘空间
+      uses: jlumbroso/free-disk-space@main
+      with:
+        tool-cache: false
+        android: true
+        dotnet: true
+        haskell: true
+        large-packages: true
+        docker-images: true
+        swap-storage: true
+
     - name: Checkout
       uses: actions/checkout@main
 
@@ -47,6 +59,7 @@ jobs:
       run: |
         sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
         sudo docker image prune --all --force
+        sudo sed -i 's/azure\.//' /etc/apt/sources.list
         sudo -E apt-get -qq update
         sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
         sudo -E apt-get -qq autoremove --purge
@@ -102,13 +115,25 @@ jobs:
     - name: Compile the firmware
       id: compile
       run: |
+        set -e
         cd openwrt
         echo -e "$(nproc) thread compile"
-        make -j$(nproc) || make -j1 || make -j1 V=s
+        echo "status=failed" >> $GITHUB_OUTPUT
+        if ! ( make -j$(nproc) || make -j1 || make -j1 V=s ); then
+            echo "❌ Make failed"
+            exit 1
+        fi
         echo "status=success" >> $GITHUB_OUTPUT
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+
+    - name: 生成直刷包
+      if: steps.compile.outputs.status == 'success'
+      run: |
+        chmod +x $GEN_BURN_IMG_SH
+        chmod +x AmlImg
+        $GITHUB_WORKSPACE/$GEN_BURN_IMG_SH
 
     - name: Check space usage
       if: (!cancelled())
